//
// Copyright (C) 2024 Harshit Jain <dev-harsh1998@hotmail.com>
//
// SPDX-License-Identifier: Apache-2.0
//
//! Service implementation for custom.hardware.hwcontrol.IHwControl.
use custom_hardware_hwcontrol::aidl::custom::hardware::hwcontrol::IHwControl::BnHwControl;
/// The binder module is generated by AIDL. It contains the binder glue code.
/// Look into: out/soong/.intermediates/device/xiaomi/nabu/aidl/hwcontrol/custom.hardware.hwcontrol-V1-rust-source/gen/custom/hardware/hwcontrol/IHwControl
use custom_hardware_hwcontrol::binder;

mod hwcontrol;
use hwcontrol::HwControl;

fn main() {
    let svc_name = "custom.hardware.hwcontrol.IHwControl/default";
    let svc = HwControl;
    let svc_binder = BnHwControl::new_binder(svc, binder::BinderFeatures::default());
    binder::add_service(svc_name, svc_binder.as_binder()).expect("Failed to add service to binder");
    binder::ProcessState::join_thread_pool()
}